# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 위지훈 (Wi Ji Hoon)
title: Junior Back-End Developer
email: wijihoon123@naver.com
website: https://velog.io/@wijihoon123

# Social links
github_username: wijihoon
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: 준현-이-043767168
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  나이 : 27 세 (1995년 생)

  최종 학력 : 대학원 (미정)

  사는 곳 : 서울특별시

  사용 기술 : <mark>Java</mark> <mark>JavaScript</mark> <mark>Spring</mark> <mark>Node</mark> <mark>React</mark>

  <mark>Back-end</mark> 개발자를 목표로 하고있습니다.

#연락처 : 010 - 9819 - 7168

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# test Section
# test_title: test

# More Section
more_title: 그 밖에 활동
more_content: | # this will include new lines to allow paragraphs
  - [개인 블로그](https://pro-dev.tistory.com/)

# Footer
footer_show_references: true

# Build settings
livereload: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
